In [1]:
import pandas as pd

In [12]:
a=pd.read_excel("prophet.xlsx")

In [13]:
a.columns

Index(['Id', 'dynamic_without_external', 'day_per_day_without_external',
       'dynamic_with_weather', 'day_per_day_with_weather',
       'dynamic_with_promotion', 'day_per_day_with_promotion'],
      dtype='object')

In [14]:
a.drop("dynamic_with_promotion",inplace=True, axis=1)

In [15]:
a.drop("day_per_day_with_promotion",inplace=True, axis=1)

In [16]:
a.to_excel("prophet.xlsx")

In [18]:
b=pd.read_excel("prophet.xlsx")

In [19]:
b

,Id,dynamic_without_external,day_per_day_without_external,dynamic_with_weather,day_per_day_with_weather
0,154,8.004709,7.546973,7.669842,7.495210
1,156,9.423813,8.878799,9.379395,9.145020
2,157,6.580283,7.153538,7.371773,7.487705
3,158,13.021152,11.651529,NaN,NaN
4,159,24.103730,24.893185,NaN,NaN
5,160,12.035362,12.280814,12.177584,12.384150
6,161,12.376777,11.680926,NaN,NaN
7,162,18.790726,18.133235,NaN,NaN
8,163,27.885496,21.661023,23.978947,20.914445
9,164,10.113327,9.394859,NaN,NaN
10,175,53.898392,50.352783,NaN,NaN
11,176,28.486416,25.839121,NaN,NaN
12,177,31.416877,41.797767,NaN,NaN
13,178,36.457910,33.648044,NaN,NaN
14,182,382.786988,349.858140,NaN,NaN
15,183,15.138072,14.659603,NaN,NaN
16,184,26.931131,27.248659,NaN,NaN
17,185,7.189609,5.782894,NaN,NaN
18,186,24.461677,24.779140,NaN,NaN
19,189,30.890387,24.033844,NaN,NaN
20,190,38.407086,30.807089,NaN,NaN
21,191,9.058090,7.019112,NaN,NaN
22,192,25.010226,24.343382,NaN,NaN
23,193,5.273749,5.418831,NaN,NaN
24,194,15.452871,15.664186,NaN,NaN
25,195,10.241191,7.038327,NaN,NaN
26,196,16.970832,12.450375,NaN,NaN
27,197,31.199130,27.535108,NaN,NaN
28,198,7.593660,8.592524,NaN,NaN
29,199,4.523189,3.943804,5.237205,4.233663
...,...,...,...,...,...
178,2493,77.208619,40.077519,NaN,NaN
179,2494,75.536007,83.282309,NaN,NaN
180,2495,185.517350,183.650968,NaN,NaN
181,2496,173.178091,26.068881,NaN,NaN
182,2497,22.763294,33.875635,NaN,NaN
183,2498,14.576289,15.877843,NaN,NaN
184,2499,91.882402,60.895316,NaN,NaN
185,2500,48.622574,33.233812,NaN,NaN
186,2501,34.903257,41.501076,NaN,NaN
187,2502,37.848608,34.663736,NaN,NaN
188,2503,31.823416,28.775286,NaN,NaN
189,2504,41.507041,44.683410,NaN,NaN
190,2506,54.982097,56.079132,NaN,NaN
191,2507,14.603305,14.435886,NaN,NaN
192,2508,22.497484,20.014237,NaN,NaN
193,2509,24.508306,24.932423,NaN,NaN
194,2514,21.453498,21.590757,NaN,NaN
195,2515,18.768681,17.933148,NaN,NaN
196,2516,10.332809,9.150597,NaN,NaN
197,2517,11.354532,11.467933,NaN,NaN
198,2518,65.277546,56.095477,NaN,NaN
199,2519,16.162848,15.893326,NaN,NaN
200,2520,28.109942,24.641029,NaN,NaN
201,2521,30.346002,17.986779,NaN,NaN
202,2525,13.804796,11.255007,NaN,NaN
203,2526,58.029756,50.968584,NaN,NaN
204,2527,15.664649,16.257680,NaN,NaN
205,2528,27.690728,25.861825,NaN,NaN
206,2529,14.905181,13.889530,NaN,NaN
207,2530,11.138521,11.142638,NaN,NaN